version: '3'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./test/resourcebridge/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # - /etc/hackrva/mqtt.passwordfile:/mosquitto/config/mqtt.passwordfile
    ports:
      - '8883:8883'
      - '1883:1883'
    networks:
      - membership
    restart: unless-stopped

networks:
  membership:
        external: false
