version: "3"
services:
    memberserver:
        build: .
        ports: 
            - 3000:3000
        # volumes: 
        #     - .src/:/membership
        depends_on:
            - postgres
        networks:
            - membership
        environment:
            - DATABASE_URL=postgresql://test:test@postgres:5432/membership
            - MEMBER_SERVER_CONFIG_FILE=${MEMBER_SERVER_CONFIG_FILE}
        volumes:
            # This is go modules cache, without it you will have to
            # re-download all dependencies after restarting container
            - modules:/go/pkg/mod/cache
            - /etc/hackrva/:/etc/hackrva/
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
          - POSTGRES_DB=membership
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
        volumes:
            - ./test/postgres/:/docker-entrypoint-initdb.d/
        networks:
            - membership

networks:
    membership:
        external: false

volumes:
    modules:
        driver: local
