version: "3"
services:
    memberserver:
        build: .
        ports:
            - 3000:3000
        # volumes:
        #     - .src/:/membership
        environment:
            - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
            - DATABASE_URL=${DATABASE_URL}
            - MEMBER_SERVER_CONFIG_FILE=${MEMBER_SERVER_CONFIG_FILE}
            - MQTT_BROKER_ADDRESS=${MQTT_BROKER_ADDRESS}
        volumes:
            # This is go modules cache, without it you will have to
            # re-download all dependencies after restarting container
            - modules:/go/pkg/mod/cache
            - /etc/hackrva/:/etc/hackrva/
volumes:
    modules:
        driver: local